const pick = (arr, i) => arr[i % arr.length];
const pad = (n, w=4) => String(n).padStart(w,'0');
const cities = [
  ['Pune','Pune Division',['Shivajinagar','Hadapsar','Kothrud','Hinjewadi','Chakan']],
  ['Mumbai','Mumbai Division',['Andheri','Kurla','Dadar','Bandra','Fort']],
  ['Nagpur','Nagpur Division',['Sitabuldi','Hingna','Jaripatka','Sadar']],
  ['Nashik','Nashik Division',['Panchavati','Satpur','Nashik Road']],
  ['Aurangabad','Aurangabad Division',['CIDCO','Waluj','Chikalthana']],
  ['Thane','Thane Division',['Wagle Estate','Mumbra','Kalwa','Ghodbunder']],
];
const categories = ['Cyber Fraud','Organized Freight Theft','Financial Crime','Vehicle Theft','Digital Extortion','Smuggling','Narcotics','Document Fraud','Human Trafficking','Illegal Arms','Property Crime','Identity Theft'];
const statuses = ['Active','Under Investigation','Court Pending','Closed/Archived'];
const names = ['Aarav Kulkarni','Rohan Patil','Aditya Deshmukh','Kabir Shah','Vivek Jadhav','Nikhil Pawar','Arjun More','Siddhant Joshi','Karan Mehta','Rahul Naik','Ishaan Rao','Manav Shinde','Yash Bhosale','Omkar Kale','Samar Gupta','Neeraj Soni','Amit Verma','Raj Malhotra','Sahil Khan','Devendra Pawar','Ananya Joshi','Meera Nair','Kavya Shah','Priya Desai','Riya Kulkarni','Sneha Patil','Pooja More','Naina Rao','Ira Mehta','Tara Bhosale','Maya Jadhav','Aisha Khan','Simran Soni','Diya Verma','Rhea Malhotra','Sana Sheikh','Avni Gupta','Ishita Naik','Nandini Kale','Kiara Shinde'];
const officers = ['INS-1042','SI-2087','ACP-4022','SP-5027','DCP-6033','DIG-7044'];
export function generateDemoDataset() {
  const persons = Array.from({length:120}, (_, i) => { const city=pick(cities,i); return {id:`PER-${pad(i+1,3)}`,fullName:`${pick(names,i)}${i>=names.length?` ${Math.floor(i/names.length)+1}`:''}`,alias:`ALPHA-${pad(i+1,3)}`,age:24+(i%37),dob:`${1978+(i%22)}-${String((i%12)+1).padStart(2,'0')}-${String((i%27)+1).padStart(2,'0')}`,gender:i%3===0?'Female':'Male',occupation:pick(['Logistics Operator','Trader','Software Consultant','Driver','Accountant','Broker','Business Owner','Technician'],i),status:pick(['Person of Interest','Subject','Associated Person','Reported Connection','Background Monitor'],i),riskAssessment:pick(['For Investigation Review','Priority Attention','Cross-Case Linkage','Under Routine Monitoring'],i),phoneNumbers:[`+91-98${String(10000000+i).slice(-8)}`],emails:[`entity${i+1}@nexus-demo.invalid`],knownLocations:[pick(city[2],i)],primaryCity:city[0],jurisdictionArea:pick(city[2],i),jurisdictionCity:city[0],jurisdictionDivision:city[1],vehicles:[`MH${10+(i%40)}-${String.fromCharCode(65+(i%26))}-${1000+i}`],cases:[],networkGroup:`Network ${String.fromCharCode(65+(i%6))}`,tags:[pick(['telecom','finance','logistics','cyber','mobility','document'],i)],summary:'Synthetic demonstration entity for NEXUS development and testing.',clearanceRequired:i%11===0?'L2_SECRET':'L1_RESTRICTED',profileCreated:'2026-01-01T00:00:00.000Z',lastActive:`2026-09-${String((i%9)+1).padStart(2,'0')}T10:00:00.000Z`}; });
  const cases = Array.from({length:500}, (_, i) => { const n=i+1,city=pick(cities,i),category=pick(categories,i*7),personCount=2+(i%7),associatedPersons=Array.from({length:personCount},(_,j)=>persons[(i*3+j*11)%persons.length].id),opened=`${2025+(i%2)}-${String((i%12)+1).padStart(2,'0')}-${String((i%27)+1).padStart(2,'0')}`; associatedPersons.forEach(pid=>persons.find(p=>p.id===pid)?.cases.push(`CASE-${1000+n}`)); return {id:`CASE-${1000+n}`,title:`Operation ${pick(['Trident','Sentinel','Aegis','Vajra','Sahyadri','Blue Shield','Iron Grid','Nightwatch','Prism','Falcon'],i)}-${pad(n,3)}`,category,status:pick(statuses,i*3),openedDate:opened,investigatingOfficer:['Insp. Vikram Deshmukh','SI Ananya Roy','ACP Arvind Rao','SP Neha Kulkarni','DCP Sameer Patil','DIG Rohan Mehta'][i%6],officerBadge:`MH-INV-${1000+i%9000}`,description:`Synthetic CCTNS-compatible investigation record for ${category.toLowerCase()}. No real person or case is represented.`,primaryJurisdiction:`${pick(city[2],i)}, ${city[0]}`,jurisdictionArea:pick(city[2],i),jurisdictionCity:city[0],jurisdictionDivision:city[1],associatedPersons,associatedLocations:[`${pick(city[2],i)} Police Station`,`${city[0]} Transit Hub`],evidenceCount:8+(i%93),linkedTips:[],clearanceRequired:i%13===0?'L2_SECRET':'L1_RESTRICTED',financialVolumeINR:25000+((i*7919)%9000000),cctnsFirNumber:`CCTNS/${city[0].toUpperCase().slice(0,3)}/${2025+(i%2)}/${pad(n,6)}`,sourceSystem:'CCTNS-DEMO-ADAPTER'}; });
  const relationships=Array.from({length:900},(_,i)=>{const source=persons[i%persons.length],target=persons[(i*17+13)%persons.length];return{id:`REL-${pad(i+1,5)}`,sourceId:source.id,targetId:target.id,sourceType:'person',targetType:'person',relationshipType:pick(['Known Associate','Communication','Shared Location','Financial Link','Case Association','Reported Relationship'],i),label:'Synthetic analytical relationship',confidence:55+(i%46),verificationStatus:i%5===0?'Verified':'Under Investigation',notes:'Synthetic demo relationship.',firstObserved:`2026-${String((i%9)+1).padStart(2,'0')}-${String((i%27)+1).padStart(2,'0')}`};});
  const transactions=Array.from({length:1200},(_,i)=>{const a=persons[i%persons.length],b=persons[(i*7+5)%persons.length];return{id:`TXN-${pad(i+1,6)}`,date:`2026-${String((i%9)+1).padStart(2,'0')}-${String((i%27)+1).padStart(2,'0')}`,amount:5000+(i*9173)%2500000,currency:'INR',sender:a.fullName,senderId:a.id,receiver:b.fullName,receiverId:b.id,category:pick(['Bank Transfer','UPI','Cash Deposit','Wallet','NEFT','RTGS'],i),flag:i%17===0?'High Value Layering':i%11===0?'Suspicious Frequency':'Normal',bankReference:`NEXUS-${pad(i+1,10)}`,channel:pick(['UPI','IMPS','NEFT','RTGS'],i)};});
  return {persons,cases,relationships,transactions,tips:[]};
}
export { officers };
